FROM python:3.6.1

# Install Required Python Modules
RUN pip install mongo-connector && pip install elastic2-doc-manager[elastic5] && \
pip install pymongo && pip install elasticsearch

# Install Mongo Tools & Shell
# bugfix https://stackoverflow.com/questions/55386246/w-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-updates-main-binary
RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
# add to package list https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
RUN echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list
# install
RUN apt-get update
RUN apt-get install -y mongodb-org-tools mongodb-org-shell

# Copy Required Scripts
WORKDIR /usr/src/connector
COPY start-schulcloud-content-mongodb-connector.sh check-schulcloud-content-mongodb-connector.py ./
COPY backup ./backup

CMD ["python", "-u", "/usr/src/connector/check-schulcloud-content-mongodb-connector.py"]
